lista1 = ["Dieimes", "Nunes", "Souza","Caio","Luana"]
print(type(lista1))
print(len(lista1))
print(lista1[4])

lista2 = lista1 *2 

print(lista2)

lista1.append("Amanda") # para adicionar elementos, podemos utilizar o método append #
print(lista1)

lista1.remove("Caio") #para remover elementos em uma lista, temos dois métodos: remove() para remoção pelo
print(lista1)         

for listageral in lista1:
    print (listageral)
    

